import time


def game_start():
  print("    ****************************************************")
  print("    *                                                  *")
  print("    *     Hello and welcome to the trials of life!     *")
  print("    *              Please enter your name              *")
  print("    *                                                  *")
  print("    ****************************************************")
  name = input("enter your name: ")


def meet_evan():
  print("    ****************************************************")
  print("    *                                                  *")
  print("    *  Here we see 'name', working in the modern era!  *")
  print("    *             But life is unsatisfactory,          *")
  print("    *          For what purpose does one live?         *")
  print("    *     you find yourself not quite understanding    *")
  print("    *      quite what your doing on this floating      *")
  print("    *                   ball of dirt.                  *")
  print("    *                                                  *")
  print("    *    I mean you have heard it all! Heaven, Hell,   *")
  print("    *         even the flying spagehetti monster!      *")
  print("    *                                                  *")
  print("    *    None of what you have heard has given you     *")
  print("    *       a satisfactory answer however, until...    *")
  print("    *                                                  *")
  print("    *   On your way home from work your meet Evan      *")
  print("    *    Now for some reason he is always joyful...    *")
  print("    *   He seems to be someone who can do no wrong     *")
  print("    *                                                  *")
  print("    *               The worst part is...               *")
  print("    *    He insists that he does wrong all the time?   *")
  print("    *                                                  *")
  print("    * One day you finally ask Evan what is his secret? *")
  print("    *            what does he look forward to?         *")
  print("    *                                                  *")
  print("    *      He explains that he looks forward to the    *")
  print("    *                  Celestial city!                 *")
  print("    *                                                  *")
  print("    *       You wonder if you can go aswell...         *")
  print("    *you resolve to follow him and set out on a journey*")
  print("    *                                                  *")
  print("    ****************************************************")



def red_book():
  print("    ****************************************************")
  print("    *                                                  *")
  print('    *   When you tell this to Evan...He is extatict!   *')
  print("    *      He then hands you a little reddish book     *")
  print("    *                This will help you,               *")
  print("    *it will show you how to get to the celestial city!*")
  print("    *                                                  *")
  print("    * You are elated...but a sense of sobriety hits you*")
  print("    *                                                  *")
  print("    *      what about my family? what will they say?   *")
  print("    *          you go to them and try and plead        *")
  print("    *   but in the end they reject you and your book   *")
  print("    * They tell you to choose between the book or them *")
  print("    * you try to explain yourself...but all is in vain *")
  print("    *                                                  *")
  print("    *   The city you live in...will soon be destroyed  *")
  print("    * But none seem to be concerned, all go about life *")
  print("    *      Now you Have a choice...will you leave?     *")
  print("    *    Or will you stay...and be destroyed along     *")
  print("    *         with your family? (Leave or Stay)        *")
  print("    *                                                  *")
  print("    ****************************************************")
  answer1 = input('Enter your choice: ')
  
  if answer1 == 'Leave':
    print("    ****************************************************")
    print("    *                                                  *")
    print("    *          It maybe a bitter seperation,           *")
    print("    * but you have made the right decision, your family*")
    print("    *  seeing your example, will soon follow your path *")
    print("    *  out of destruction and into the celestial city  *")
    print("    *                                                  *")
    print("    ****************************************************")

  elif answer1 == 'Stay':
    print("    ****************************************************")
    print("    *                                                  *")
    print("    *          You have resolved to stay...            *")
    print("    *     You have aknowledged danger but yet stay     *")
    print("    *You cannot stay here or else it will lead to death*")
    print("    *          you must leave! (type Leave)            *")
    print("    *                                                  *")
    print("    ****************************************************")
    answer2 = input('Try Again: ')
    if answer2 == 'Leave':
      print("    ****************************************************")
      print("    *                                                  *")
      print("    *          It maybe a bitter seperation,           *")
      print("    * but you have made the right decision, your family*")
      print("    *  seeing your example, will soon follow your path *")
      print("    *  out of destruction and into the celestial city  *")
      print("    *                                                  *")
      print("    ****************************************************")
  else:
    print("    ****************************************************")
    print("    *                                                  *")
    print("    *         Please try again (case sensative)        *")
    print("    *                                                  *")
    print("    ****************************************************")
    answer1 = input('Enter your choice: ')

def burden():
    print("    ****************************************************")
    print("    *                                                  *")
    print("    *    As you go about the way that Evan shows you   *")
    print("    *You continue to read the reddish book to guide you*")
    print("    * As you continue..as you read...the burden on you *")
    print("    *   grows quite large..as you realize this burden  *")
    print("    * it grows cumbersome as you continue you see a bog*")
    print("    *          as you continue on the path...          *")
    print("    *         you notice you must go through it        *")
    print("    *                                                  *")
    print("    * you start into the bog, soon realizing the burden*")
    print("    *     is weighing you down...you soon will sink    *")
    print("    *           you frantically call out 'help'        *")
    print("    *   A man by the name of Holy Help calls you name  *")
    print("    *                                                  *")
    print("    *      Brother I am here to help! grab my hand!    *")
    print("    *                  at the same time...             *")
    print("    *                                                  *")
    print("    *            you hear a man say just swim!         *")
    print("    *            you can do this one your own!         *")
    print("    *                                                  *")
    print("    *               Whose advice do you take?          *")
    print("    *  do you choose to Swim or take Holy Helps hand?  *")
    print("    *                                                  *")
    print("    ****************************************************")
    answer3 = input("Swim or Take Help?")

    if answer3 == "Swim" or answer3 == "swim":
      print("    ****************************************************")
      print("    *                                                  *")
      print("    *        having no burden and being perfect,       *")
      print("    *          perhaps you could have made it...       *")
      print("    *              but that is not the case            *")
      print("    *     would it not be simpler to take the hand?    *")
      print("    *                                                  *")
      print("    ****************************************************")
    elif answer3 == "Take Help":
      print("    ****************************************************")
      print("    *                                                  *")
      print("    * Help has been sent specifically for this purpose *")
      print("    * He has been set on this path to help you through *")
      print("    *                 the bog of despair               *")
      print("    *             To taked his hand is wise            *")
      print("    *     Because of this decision...you made it out   *")
      print("    *                                                  *")
      print("    ****************************************************")
    else:
      print("    ****************************************************")
      print("    *                                                  *")
      print("    *         Please try again (case sensative)        *")
      print("    *                                                  *")
      print("    ****************************************************")
      answer3 = input('Enter your choice: ')

def choiceOfMorality():
    print("    ****************************************************")
    print("    *                                                  *")
    print("    *            once you are out of the bog...        *")
    print("    *       you are faced with a fork in the road      *")
    print("    *  first side being the city of morality, home of  *")
    print("    *           legality and his son civility          *")
    print("    *                                                  *")
    print("    *    the other option is the straight and narrow   *")
    print("    *   this path will take you to the gate of purity  *")
    print("    *                                                  *")
    print("    *    Which will you choose? (Purity or Legality)   *")
    print("    *                                                  *")
    print("    ****************************************************")
    answer4 = input("Purity or Legality?")

    if answer4 == "Purity" or answer4 == "purity":
      print("    ****************************************************")
      print("    *                                                  *")
      print("    *              when you take this path,            *")
      print("    * you take the path directly to the celestial city *")
      print("    * the path of legality is one that will discourage *")
      print("    *the weight of rules and regulations will break you*")
      print("    *the rules all that are in vain..none of which will*")
      print("    *       be of help in purifying you to be ready    *")
      print("    *               for the celestial city             *")
      print("    *                                                  *")
      print("    ****************************************************")
    elif answer4 == "Legality" or answer4 == "legality":
      print("    ****************************************************")
      print("    *                        **                        *")
      print("    *          you chose the path of legality          *")
      print("    * you once again thought that you could find a way *")
      print("    *   to rid yourself of this burden by yourself     *")
      print("    *                                                  *")
      print("    *      after reading the book, you notice that     *")
      print("    *            the burden on your back               *")
      print("    *      is simply the sin and evil you have done    *")
      print("    *    to try and stop that yourself...is foolish    *")
      print("    *you should try staying on the straight and narrow *")
      print("    *                                                  *")
      print("    ****************************************************")
      choiceOfMorality()
    else:
      print("    ****************************************************")
      print("    *                                                  *")
      print("    *         Please try again (case sensitive)        *")
      print("    *                                                  *")
      print("    ****************************************************")
      choiceOfMorality()

def interpreter():
    print("    ****************************************************")
    print("    *                                                  *")
    print("    *         when you get to the gate of purity       *")
    print("    *     the gate keeper, name GW, lets you through   *")
    print("    *         He tells you your next destination       *")
    print("    *                to the interpreter                *")
    print("    *                                                  *")
    print("    *         when you get to interpreters home        *")
    print("    *                 He sits you down...              *")
    print("    *        He explains the concept of grace...       *")
    print("    *      and He says something...this grace is how   *")
    print("    *    you get free of your burden of sin and evil   *")
    print("    *                                                  *")
    print("    *         you then are filled with a fire          *")
    print("    *                                                  *")
    print("    *      you then set out to see this ""cross""      *")
    print("    *                                                  *")
    print("    ****************************************************")

def cross():
    print("    ****************************************************")
    print("    *                                                  *")
    print("    *           when you get to the cross...           *")
    print("    *               you start to weep...               *")
    print("    *     when you see what has happened...you notice  *")
    print("    *              the burden is gone!!!               *")
    print("    *                                                  *")
    print("    *          oh what freedom...oh what joy!          *")
    print("    *        you then continue on your journey         *")
    print("    *        trials may come, tribulations too...      *")
    print("    *      but you know the cross has set you free     *")
    print("    *           so you do not fret nor fear!           *")
    print("    *                                                  *")
    print("    ****************************************************")


    


game_start()


meet_evan()

red_book()

burden()

choiceOfMorality()

interpreter()

cross()



   

